# An experimental AppVeyor config to install Strawberry Perl and
# Rakudo Star. Once installed, AppVeyor caches those for use next time.
#
# I specifically don't build Rakudo from GitHub because I want to use
# the "normal people" release.

# AppVeyor on Linux: https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#running-windows-and-linux-builds-side-by-side
# AppVeyor environment variables: https://www.appveyor.com/docs/environment-variables/

image:
  - Visual Studio 2015
  - Ubuntu

platform: x64

branches:
  only:
    - master

# set your own environment variables here.
#
# Perl 5's Test::Harness has several env variables (many appear as prove switches)
#   https://metacpan.org/pod/Test::Harness

environment:
  MY_VAR: true
  MSIEXEC_WAIT_SECONDS: 10
  AUTOMATED_TESTING: 1
  TEST_VERBOSE: 0
  HARNESS_OPTIONS:
  HARNESS_VERBOSE: 0
  HARNESS_TIMER: 1
  HARNESS_PERL_SWITCHES: -MDevel::Cover
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  TEMPDIR: /tmp
  RAKUDO_PKG_URL: https://github.com/nxadm/rakudo-pkg/releases/download/v2018.02.1/rakudo-pkg-Ubuntu14.04_2018.02.1-01_amd64.deb

install:
  # Install Strawberry Perl with chocolately.
  # Strawberry Perl comes with `prove`, which we use to run the tests.
  # http://strawberryperl.com
  # https://chocolatey.org/packages/StrawberryPerl
  - cmd: if not exist "C:\Strawberry" cinst strawberryperl
  - cmd: SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - ps: refreshenv
  - sh: sudo apt-get install build-essential git libssl-dev
  - sh: sudo apt-get install -y perl
  - perl -v
  # Install Rakudo Star with chocolately.
  # https://chocolatey.org/packages/rakudostar
  - cmd: if not exist "C:\Rakudo" cinst rakudostar
  - cmd: SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%
  - ps: refreshenv
  # Ubuntu install
  - sh: cd ${TEMPDIR}
  - sh: wget -O rakudo-pkg.deb ${RAKUDO_PKG_URL}
  - sh: sudo dpkg -i rakudo-pkg.deb
  - sh: export PATH=$PATH:~/.perl6/bin:/opt/rakudo-pkg/bin
  - sh: git clone https://github.com/ugexe/zef.git && cd zef && perl6 -Ilib bin/zef install .
  - perl6 -v

build: off

# many of the settings in `environment` affect what happens in the test script
#
# I'd like to run Devel::Cover and submit to Coveralls too.
test_script:
  - prove -v -e "perl6 -Ilib" t/

shallow_clone: true
